### ISSUE TITLE
dictutil: `key_path`支持tuple和list格式.

### ISSUE THREAD

**Issue by drmingdrmer** [baishancloud/pykit#159]
涉及到的几个函数:
- get
- make_getter
- make_getter_str
- make_setter

上面这几个函数现在`key_path`参数是dot分隔的string, 像: `"foo.bar"`, 表示: `my_dict["foo"]["bar"]`.

需要支持tuple/list格式的`key_path`, 以支持更复杂的字典访问, 类似: `("foo", "bar")` 表示: `my_dict["foo"]["bar"]`

**Comment by tongwei** [comment]
https://github.com/baishancloud/pykit/pull/164
