### ISSUE TITLE
new module: `cluster.drive`

### ISSUE THREAD

**Issue by drmingdrmer** [baishancloud/pykit#194]
参考: `s2/src/partition.py`

所需功能:
dependency:
- `cluster.server` #193

**Comment by pengsven** [comment]
收集drive如下些统计信息是否考虑收入这个module里，
    # {
    #  'fs': 'ext4',
    #  'media_type': 'ATA',
    #  'media_error': 0,
    #  'uuid': 'eefa8238-067e-4bfc-8d30-364549ceeb95',
    #  'space': 1912908521472L,
    #  'capacity': 1968464289792L,
    #  'ioutil': 0,
    #  'read': 589824,
    #  'write': 0,
    #  'readable': True,
    #  'writable': True,
    #  'fail': False,
    # }

**Comment by drmingdrmer** [comment]
目前实时信息收集的打算放别的模块里, 这个只做管理磁盘用. 还没太想好. 感觉先最小化设计, 后面有需要再加进来也没啥问题.
