### ISSUE TITLE
add more doc to strutil

### ISSUE THREAD

**Issue by drmingdrmer** [baishancloud/pykit#30]
add doc of functions:
- tokenize
- colorize
- ColoredString

merge function: `utf8str` and `to_output_format`

**Comment by sejust** [comment]
#85

**Comment by drmingdrmer** [comment]
你可以在commit message里加 `Fix: #30` 来直接在merge到master时关闭1个issue~.

https://github.com/blog/1506-closing-issues-via-pull-requests

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by sejust** [comment]
好的
