### ISSUE TITLE
fsutil: +1个函数: calc_chechksum(path, ...)

### ISSUE THREAD

**Issue by drmingdrmer** [baishancloud/pykit#91]
`def calc_checksum(path, sha1=True, md5=True, crc32=True, block_size=32*1024**2, iolimit=32*1024**2)`

计算本地磁盘上文件的sha1, md5, 或crc32(1个或多个).
可以指定1次文件读取的块大小(默认32MB), 也可以指定io开销的限制(默认1秒32MB).

参考: s2 项目中 fs.py: `get_file_checksums()`

**Comment by sejust** [comment]
```c4883f687f0342ddaf9402db5fc7623ac482b345```
